# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='question',
            field=models.ForeignKey(default=41, on_delete=django.db.models.deletion.CASCADE, to='vote.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('user', 'question')]),
        ),
    ]
