# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
