# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='name',
            new_name='title',
        ),
    ]
