# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_auto_20160204_0956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='owner',
        ),
    ]
