# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20160204_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
