# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_auto_20160204_1104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='response',
            unique_together=set([('user', 'answer')]),
        ),
    ]
