# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20160217_1536'),
        ('vote', '0004_auto_20160217_1520'),
    ]

    operations = [
    ]
