# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 14:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='questiongroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 19, 14, 0, 10, 609330, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
