# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 14:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_questiongroup_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='date_time',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='answer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 19, 14, 16, 10, 29598, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 19, 14, 16, 20, 975577, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 19, 14, 16, 28, 685098, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
